security:
    oauth2:
        client:
            clientId: 723068959254-f522es0iva0ecd514qcini5932j2a1gr.apps.googleusercontent.com
            clientSecret: ysbZRM-VyVIW535g_6WUzxYD
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: profile email
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false
            
management:
    security:
        enabled: false
    port: 8081
    
spring:
    data:
        mongodb:
            uri: mongodb://estagiarios:estagiarios@localhost:27017/estagiarios
            authentication-database: estagiarios
  